export const productsList = [
  {
    name: "Apple notebook Macbook Pro M3",
    price: 13499.99,
    id: 0,
    description: [
      "COM A POTÊNCIA DO CHIP M3 - Faça voando suas atividades diárias em vários apps e trabalhe em projetos profissionais, como edição de milhares de fotos ou vídeos 4K. O chip M3 vem com CPU de 8 núcleose GPU de 10 núcleos com traçado de raios acelerado por hardware.",
      "ATÉ 22 HORAS DE BATERIA - Aproveite o computador por mais tempo com o consumo eficiente de energiado chip da Apple. O MacBook Pro oferece o mesmo alto desempenho, ligado na tomada ou na bateria.",
      "MEMÓRIA UNIFICADA E ARMAZENAMENTO RESPONSIVOS - Até 24 GB de memória unificada para seutrabalho fluir com velocidade. Até 2 TB de armazenamento SSD ultrarrápido para abrir apps e arquivos num instante",
      "TELA PROFISSIONAL BRILHANTE - As 14,2 polegadas da tela Liquid Retina XDR3 exibem Extreme DynamicRange, 1.000 nits de brilho constante para conteúdo HDR, até 600 nits de brilho para conteúdo SDR e modosde imagem profissionais. Faça seu melhor trabalho em qualquer lugar",
    ],
    stock: 10,
    author: "Apple Inc.",
    evaluation: 4.4,
    img: "https://cdn.pixabay.com/photo/2022/03/04/10/17/technology-7046991_1280.jpg",
  },
  {
    name: "Apple iPhone 14 (128 GB)",
    price: 3869.99,
    id: 1,
    description: [
      "Tela Super Retina XDR de 6,1 polegadas",
      "Sistema de câmera avançado para fotos melhores em qualquer luz",
      "Modo Cinema, agora em 4K Dolby Vision até 30 qps",
      "Modo Ação para vídeos em movimento com mais estabilidade",
      "Tecnologia de segurança — Detecção de Acidente, que liga para a emergência se você não puder",
    ],
    stock: 82,
    author: "Apple Inc.",
    evaluation: 4.8,
    img: "https://cdn.pixabay.com/photo/2022/09/25/22/25/iphones-7479304_1280.jpg",
  },
  {
    name: "Cafeteira espresso Delonghi Caffe'Corso",
    price: 2499.99,
    id: 2,
    description: [
      "20 BAR DE PRESSÃO - SABOR INTENSO + CAFÉ CREMOSO: A cafeteira espresso Delonghi Caffe`Corso possui a alta pressão de 20 Bar e garante uma extração de alta qualidade e sabor único;",
      "2 XÍCARAS DE UMA VEZ: O Porta Filtro com duas saídas prepara até 2 xícaras por vez;",
      "BICO VAPORIZADOR: Permite que você prepare facilmente uma espuma de leite suave e cremosa para criar diversas bebidas, como cappuccino, mocha, macchiato, frappuccino e muito mais;",
      "POTÊNCIA - 1200W: Extrai um café saboroso, aromático e cremoso em apenas 18 segundos. Incrível, né?;",
      "CAPACIDADE - 1,2 LITROS: O reservatório de água com capacidade de 1,2 litros é removível e facilita o reabastecimento e recolocação. Prepara até 30 xícaras de 40ml (cada).",
    ],
    stock: 3,
    author: "Delonghi",
    evaluation: 4.7,
    img: "https://cdn.pixabay.com/photo/2013/12/22/03/29/tea-232118_1280.jpg",
  },
  {
    name: "Monitor Dell 27' S2721HN",
    price: 1186.55,
    id: 4,
    description: [
      "Design moderno e elegante com um padrão sutil de textura na parte de trás do monitor",
      "Portas HDMI duplas",
      "Dell EasyArrange, mantenha a organização de aplicativos",
      "Tecnologia AMD FreeSync",
      "Certificação TÜV",
    ],
    stock: 23,
    author: "Dell Inc.",
    evaluation: 4.9,
    img: "https://m.media-amazon.com/images/I/71vkYtEoGgL._AC_SL1280_.jpg",
  },
  {
    name: "Keychron K3 Teclado Mecânico - Ultrathin Portátil",
    price: 999.99,
    id: 5,
    description: [
      "Keychron K3, um teclado mecânico compacto com 75% de layout RGB de 84 teclas RGB de troca a quente, ultrafino, construído para máxima produtividade, uma ótima experiência de digitação tátil e permite que você personalize a experiência de digitação por tecla sem solda.",
      "Esteja pronto para realizar várias tarefas sem perder o ritmo, conectando o K3 a até 3 dispositivos através do chipset Bluetooth 5.1 estável e alterne entre seu laptop, PC, tablet e telefone perfeitamente. Ele também tem modo com fio com conexão USB tipo C.",
      "Com um layout exclusivo para Mac, o K3 tem todas as teclas multimídia necessárias para Mac enquanto ainda é compatível com Windows. Teclas extras para sistemas operacionais Windows e Mac estão incluídas.",
    ],
    stock: 242,
    author: "Keychron-Nuphy",
    evaluation: 4.4,
    img: "https://m.media-amazon.com/images/I/61Z6jPiK5CL._AC_SL1500_.jpg",
  },
  {
    name: "Keychron Teclado mecânico V2 com fio personalizado",
    price: 795.99,
    id: 6,
    description: [
      "Teclado mecânico de 66 teclas: o V2 tem um layout ultracompacto de 65% com suporte QMK/VIA, que pode oferecer infinitas possibilidades de personalização e atender às suas necessidades em diferentes situações. Com teclas PBT de disparo duplo, uma almofada de silicone acústica e interruptores pré-lubrificados, garante a melhor experiência de digitação.",
      "Totalmente personalizável de dentro para fora: para construir um teclado totalmente personalizável, projetamos todos os componentes facilmente montados, incluindo teclas, interruptores, vedações, placas, botão e espuma da capa, se você quiser. Com suporte QMK e VIA, você pode facilmente programar e remapear cada tecla no teclado. O firmware de código aberto significa infinitas possibilidades para layouts de teclado, atalhos, efeitos de luz de fundo e muito mais.",
      'Suporte trocável: com o interruptor tátil mecânico pré-lubrificado marrom que fornece uma resposta tátil incomparável com até 50 milhões de teclas de vida útil. Você também pode trocar o V2 com quase todos os interruptores mecânicos MX de 3 pinos e 5 pinos no mercado (incluindo Cherry, Gateron, Kailh, Panda, etc.) sem necessidade de soldagem. O estabilizador de parafuso montado em PCB para "teclas grandes" como barra de espaço, shift, enter e delete é projetado para menos oscilação e desempenho suave.',
    ],
    stock: 101,
    author: "Keychron-Nuphy",
    evaluation: 4.7,
    img: "https://m.media-amazon.com/images/I/61tgINp50NL._AC_SL1500_.jpg",
  },
  {
    name: "Mouse sem fio Logitech MX Master 3S com Sensor Darkfield",
    price: 568.3,
    id: 7,
    description: [
      "Tracking em qualquer superfície - agora 8K DPI: use o MX Master 3S em qualquer superfície - até em vidro - com o sensor atualizado de 8000 DPI com sensibilidade personalizável",
      "Cliques silenciosos: o mouse sem fio MX Master 3S conta com cliques silenciosos - mantendo a mesma sensação satisfatória, mas com 90% menos ruído de clique",
      "Rolagem Magspeed: um mouse com notável velocidade, precisão e silêncio - a rolagem MagSpeed é 90% mais rápida, 87% mais precisa e ultra silenciosa",
    ],
    stock: 451,
    author: "Logitech.",
    evaluation: 4.9,
    img: "https://m.media-amazon.com/images/I/61ni3t1ryQL._AC_SL1500_.jpg",
  },
]
